# .github/workflows/release.yml
name: Build and release Go Project

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build project
        run: go build . && mv weiba weiba-${{ github.ref }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            weiba-${{ github.ref }}}
